[bbandsParameters]
optInTimePeriod = 20
optInNbDevUp = 1
optInNbDevDn = 1
optInMAType = 0

[thresholds]
down = -0.025
up = 0.025

[outputs]
upperBand = 'FLOAT'
middleBand = 'FLOAT'
lowerBand = 'FLOAT'
