[bbandsParameters]
optInTimePeriod = 20
optInNbDevUp = 1
optInNbDevDn = 1
optInMAType = 0

[thresholds]
up = 0.0075
down = -0.01
limit = 0.015

[outputs]
upperBand = 'FLOAT'
middleBand = 'FLOAT'
lowerBand = 'FLOAT'
longPrice = 'FLOAT'
maxPrice = 'FLOAT'
